apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
  labels:
    app: react-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - name: react-ui
        image: docker.io/sagarchhabra02/react-ui:v2.1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-ui-cluster-ip-service
  labels: 
    name: react-ui-cluster-ip-service
spec:
  selector:
    app: react-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-node-port-service
spec:
  type: NodePort
  selector:
    app: react-ui
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30008